# Generated by Django 5.0.14 on 2026-06-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(max_length=120, unique=True)),
                ('procesador', models.CharField(blank=True, max_length=120)),
                ('memoria_ram', models.CharField(blank=True, max_length=60)),
                ('almacenamiento', models.CharField(blank=True, max_length=80)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Dado de baja')], default='disponible', max_length=20)),
                ('asignado_a', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('usuario', models.CharField(max_length=80, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('mesa_tic', 'Mesa TIC'), ('frente', 'Responsable de frente'), ('mesa', 'Responsable de mesa')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('frente', 'Frente de obra'), ('mesa', 'Mesa de trabajo')], max_length=20)),
                ('responsable_nombre', models.CharField(max_length=120)),
                ('responsable_cargo', models.CharField(max_length=40)),
                ('clave', models.CharField(blank=True, max_length=30)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'Alta'), ('asignacion', 'Asignacion'), ('cambio_estado', 'Cambio de estado'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja')], max_length=30)),
                ('descripcion', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.equipo')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.responsable')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='responsable',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion'),
        ),
    ]
