# Generated by Django 5.0.14 on 2026-06-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='clave',
        ),
    ]
