# Generated by Django 5.0.14 on 2026-06-03 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_ubicacion_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tipo de equipo',
                'verbose_name_plural': 'tipos de equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='mac_ethernet',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='equipo',
            name='mac_wifi',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoequipo'),
        ),
    ]
