# Generated by Django 5.0.14 on 2026-06-05 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_solicitudtipoequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='factura',
            field=models.FileField(blank=True, upload_to='facturas/'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='asignado_a',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado_equipo',
            field=models.CharField(blank=True, choices=[('asignado', 'Asignado'), ('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Dado de baja')], max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacion'),
        ),
    ]
