# Generated by Django 5.0.14 on 2026-06-05 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def catalogar_marcas_existentes(apps, schema_editor):
    Equipo = apps.get_model('inventario', 'Equipo')
    MarcaEquipo = apps.get_model('inventario', 'MarcaEquipo')

    marcas_por_nombre = {}
    for equipo in Equipo.objects.exclude(marca=""):
        nombre = equipo.marca.strip()
        if not nombre:
            continue
        clave = nombre.lower()
        marca = marcas_por_nombre.get(clave)
        if not marca:
            marca, _ = MarcaEquipo.objects.get_or_create(nombre__iexact=nombre, defaults={"nombre": nombre})
            marcas_por_nombre[clave] = marca
        equipo.marca_equipo = marca
        equipo.marca = marca.nombre
        equipo.save(update_fields=["marca_equipo", "marca"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_equipo_factura_movimiento_asignado_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'marca de equipo',
                'verbose_name_plural': 'marcas de equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.marcaequipo'),
        ),
        migrations.CreateModel(
            name='SolicitudMarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentario_admin', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de marca de equipo',
                'verbose_name_plural': 'solicitudes de marcas de equipo',
                'ordering': ['-creado'],
            },
        ),
        migrations.RunPython(catalogar_marcas_existentes, migrations.RunPython.noop),
    ]
