# Generated by Django 5.0.14 on 2026-06-05 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_seed_marcas_equipo_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, max_length=120)),
                ('descripcion_equipo', models.CharField(max_length=260)),
                ('eliminado_por_nombre', models.CharField(blank=True, max_length=120)),
                ('eliminado_por_rol', models.CharField(blank=True, max_length=80)),
                ('ubicacion_nombre', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, choices=[('asignado', 'Asignado'), ('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Dado de baja')], max_length=20)),
                ('asignado_a', models.CharField(blank=True, max_length=120)),
                ('snapshot', models.JSONField()),
                ('eliminado', models.DateTimeField(auto_now_add=True)),
                ('eliminado_por_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.responsable')),
                ('eliminado_por_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo eliminado',
                'verbose_name_plural': 'equipos eliminados',
                'ordering': ['-eliminado'],
            },
        ),
    ]
