# Generated by Django 5.0.14 on 2026-06-06 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_equipoeliminado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='agente_usuario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='realizado_por_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='realizado_por_rol',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='realizado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('login', 'Inicio de sesion'), ('logout', 'Cierre de sesion'), ('login_fallido', 'Inicio de sesion fallido')], max_length=20)),
                ('nombre_usuario', models.CharField(blank=True, max_length=150)),
                ('responsable_nombre', models.CharField(blank=True, max_length=120)),
                ('responsable_rol', models.CharField(blank=True, max_length=80)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('direccion_ip_reenviada', models.CharField(blank=True, max_length=255)),
                ('agente_usuario', models.TextField(blank=True)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('clave_sesion', models.CharField(blank=True, max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de acceso',
                'verbose_name_plural': 'registros de acceso',
                'ordering': ['-creado'],
            },
        ),
    ]
