# Generated by Django 5.0.14 on 2026-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_movimiento_agente_usuario_movimiento_direccion_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoeliminado',
            name='agente_usuario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipoeliminado',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
