# Generated by Django 5.0.14 on 2026-06-06 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_equipoeliminado_agente_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResguardoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_a', models.CharField(max_length=120)),
                ('ubicacion_nombre', models.CharField(max_length=120)),
                ('fecha_asignacion', models.DateField()),
                ('generado_por_nombre', models.CharField(blank=True, max_length=120)),
                ('generado_desde_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('archivo_firmado', models.FileField(blank=True, upload_to='resguardos_firmados/%Y/%m/')),
                ('cargado_por_nombre', models.CharField(blank=True, max_length=120)),
                ('cargado_desde_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cargado', models.DateTimeField(blank=True, null=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resguardos_cargados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resguardos', to='inventario.equipo')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resguardos_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resguardo de equipo',
                'verbose_name_plural': 'resguardos de equipos',
                'ordering': ['-generado'],
            },
        ),
    ]
