# Generated by Django 5.0.14 on 2026-06-07 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_resguardoequipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resguardoequipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resguardoequipo',
            name='reemplazado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resguardoequipo',
            name='reemplazado_desde_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resguardoequipo',
            name='reemplazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resguardos_reemplazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resguardoequipo',
            name='reemplazado_por_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
