# Generated by Django 5.0.14 on 2026-06-08 18:10

import django.db.models.deletion
from django.db import migrations, models


def seed_santa_lucia(apps, schema_editor):
    Ubicacion = apps.get_model('inventario', 'Ubicacion')
    UbicacionFisica = apps.get_model('inventario', 'UbicacionFisica')
    Equipo = apps.get_model('inventario', 'Equipo')
    Movimiento = apps.get_model('inventario', 'Movimiento')

    physical_locations = {}
    for location in Ubicacion.objects.all():
        physical_location, _ = UbicacionFisica.objects.get_or_create(
            ubicacion=location,
            nombre='Santa Luc\u00eda',
        )
        physical_locations[location.id] = physical_location.id

    for location_id, physical_location_id in physical_locations.items():
        Equipo.objects.filter(ubicacion_id=location_id, ubicacion_fisica__isnull=True).update(
            ubicacion_fisica_id=physical_location_id
        )
        Movimiento.objects.filter(ubicacion_id=location_id, ubicacion_fisica__isnull=True).update(
            ubicacion_fisica_id=physical_location_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_resguardoequipo_activo_resguardoequipo_reemplazado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_fisicas', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'ubicacion fisica',
                'verbose_name_plural': 'ubicaciones fisicas',
                'ordering': ['ubicacion__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacionfisica'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacionfisica'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionfisica',
            constraint=models.UniqueConstraint(fields=('ubicacion', 'nombre'), name='ubicacion_fisica_unica_por_ffoo_mesa'),
        ),
        migrations.RunPython(seed_santa_lucia, migrations.RunPython.noop),
    ]
