# Generated by Django 5.0.14 on 2026-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_ubicacionfisica_equipo_ubicacion_fisica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resguardoequipo',
            name='ubicacion_fisica_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
